# Generated by Django 3.1.2 on 2021-07-21 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_time', models.DateTimeField(null=True)),
                ('sale_warehouse', models.CharField(max_length=200, null=True)),
                ('sale_id', models.CharField(max_length=200, null=True)),
                ('sale_status', models.CharField(max_length=200, null=True)),
                ('sale_updated_time', models.DateTimeField(null=True)),
                ('sale_client', models.CharField(max_length=200, null=True)),
                ('sale_name', models.CharField(max_length=200, null=True)),
                ('product_barcode', models.IntegerField(null=True)),
                ('product_name_cn', models.CharField(max_length=200, null=True)),
                ('product_name_en', models.CharField(max_length=200, null=True)),
                ('product_brand', models.CharField(max_length=200, null=True)),
                ('product_supplier', models.CharField(max_length=200, null=True)),
                ('sale_quantity', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('sale_price', models.DecimalField(decimal_places=4, max_digits=10, null=True)),
                ('sale_payment', models.DecimalField(decimal_places=4, max_digits=10, null=True)),
                ('upload_id', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
