# Generated by Django 3.1.1 on 2020-12-08 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryName', models.CharField(max_length=32)),
                ('mainCategory', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='delivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driverName', models.CharField(max_length=32, null=True)),
                ('date', models.DateField()),
                ('imgInfo', models.CharField(max_length=255, null=True)),
                ('location', models.CharField(max_length=32)),
                ('nickName', models.CharField(max_length=32, null=True)),
                ('plateNumber', models.CharField(max_length=32)),
                ('project', models.CharField(max_length=32)),
                ('quantity', models.FloatField()),
                ('receiveID', models.CharField(max_length=32)),
                ('receiverName', models.CharField(max_length=32)),
                ('time', models.TimeField()),
                ('unit', models.CharField(max_length=32)),
                ('uploadTime', models.DateTimeField()),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dash.material')),
            ],
        ),
    ]
